# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo -e "setting up node via apt-get";
          apt-get update || sudo !!;
          apt-get upgrade || sudo !!;
          apt-get install nodejs || sudo !!;
          
          echo - e "compiling project > run checks" 
          npm install --save-dev yarn;
          yarn;
          yarn build;
          yarn build:test;
          yarn test;
          
          echo -e "preparing merge with master";
          rm -rf .git;
          git init,;
          git add remote origin https://github.com/kaspardohrin/do-paginate.git;
          cd do-paginate/.;
          git add .;
          git commit -m "merge development with master";
          git merge origin master;
          git push origin develop:master;
          
          echo -e "success :)";
          
          
